USE BloodPressure;

DROP FUNCTION IF EXISTS BMI;

DELIMITER $$

CREATE FUNCTION BMI (kilos  DECIMAL(10,2))
RETURNS DECIMAL(6, 1)
DETERMINISTIC
BEGIN
    RETURN kilos / 2.89;
END$$

DELIMITER ;

DROP FUNCTION IF EXISTS CalculateCalories;

DELIMITER $$


CREATE FUNCTION CalculateCalories(fat DECIMAL(8, 3), carb DECIMAL(8, 3), protein DECIMAL(8, 3), units DECIMAL(8, 3))
RETURNS DECIMAL(8, 3)
DETERMINISTIC
BEGIN
    RETURN 4 * (IFNULL(carb, 0) + IFNULL(protein, 0)) + 9 * IFNULL(fat, 0) + 56 * IFNULL(units, 0);
END$$


DELIMITER ;

DROP FUNCTION IF EXISTS WeekStart;

DELIMITER $$

CREATE FUNCTION WeekStart(day DATE)
RETURNS DATE
DETERMINISTIC
BEGIN
    RETURN CAST(DATE_ADD(day, INTERVAL -dayofweek(day) + 1 DAY) AS DATE);
END$$

DELIMITER ;
